### ISSUE TITLE
Add tests forgotten in Milestone 3.B

### ISSUE THREAD

**Issue by nd1az** [Geo-Mafia/Geo-Mafia#23]
tests for: 
addplayer();
removeplayer();
inBubble();
returnPlayer();

**Comment by corian-jal** [comment]
Added more tests for inBubble, addPlayer, removePlayer, and returnPlayer along with upping the rigor of all map test suites.

**Comment by corian-jal** [comment]
I'm closing this issue due to completion. See PR #33
