### ISSUE TITLE
Translation for functions for app implementation

### ISSUE THREAD

**Issue by nd1az** [Geo-Mafia/Geo-Mafia#24]
Need to make .ts translations of the .js files so that angular implementation can be done on the app. This is so that it can be separate from the testing implementation that was needed from the .js files.

**Comment by noahklowden** [comment]
How is this going? Would it be helpful to have someone step in so you can focus on the other issue?

**Comment by nd1az** [comment]
Translation is going well, I have a simple Player shown in the UI atm, just need my pull request to be reviewed. Sorry I forgot to update my issue!

**Comment by nd1az** [comment]
Completed translation of the game and player components. Also generated a module and chat component to start on making those translations
