### ISSUE TITLE
Modify Chat/Player Tests to TS from JS

### ISSUE THREAD

**Issue by Strongbrother1** [Geo-Mafia/Geo-Mafia#36]
Make sure tests are compiling and passing.

**Comment by jasulcaf** [comment]
Have finished converting JS into TS; I know believe there is something wrong how QUnit tests are being made. This is because the export itself is bringing lots of issues when trying to run tests (when trying to export our files that contain class information).

**Comment by gypark23** [comment]
If you PR I'll review them and merge if it runs without issues
