### ISSUE TITLE
Design Snapshot Class

### ISSUE THREAD

**Issue by noahklowden** [Geo-Mafia/Geo-Mafia#43]
The game class requires the snapshot class to function and the game itself needs to be able to have snapshots taken. We should write up the design documentation and create the basic outline of the class.

The code in the game class that is currently commented out because it references Snapshots will need to be written in.

Once this issue is completed, a new issue should be made for writing the tests.

**Comment by Anna-Bele** [comment]
https://github.com/Geo-Mafia/Geo-Mafia/tree/snapshot
