### ISSUE TITLE
Game killing handling design

### ISSUE THREAD

**Issue by noahklowden** [Geo-Mafia/Geo-Mafia#47]
The game needs to be able to handle killing conditions. Documentation should be written up and designed such that each of these tasks can be handled:
 - count living players
 - be able to check if a player is dead
 - have a timer for a time limit end condition
 - be able to check if all killers have been voted out
 - be able to know if the killers have met the win condition

After this is complete an issue for writing up the tests should be created.

**Comment by jasulcaf** [comment]
Have created branch, will begin trying to implement above stated things

**Comment by jasulcaf** [comment]
Added functionality to see how many killers left in the game, how many civilians left in the game, how many total players are left in the game, and a winning condition function that either returns if Killers have won, Civilians have won, or if game still in progress
