### ISSUE TITLE
Configure GitHub repository/Set up GitHub Workflow

### ISSUE THREAD

**Issue by gypark23** [Geo-Mafia/Geo-Mafia#5]

**Comment by Strongbrother1** [comment]
Workflows are almost finished, working on some interacting with firebase : https://stackoverflow.com/questions/47343658/using-npm-run-build-fails-with-npm-err-missing-script-build.

Current issue is "npm run build", but after that all workflows should be good. 

If you want to see the progress as of now, it's on my branch (Strongbrother1/Geo-Mafia)

**Comment by gypark23** [comment]
I am thinking that the workflow will just consist two lines, each building iOS and Android apps:
`tns run ios`
`tns run android`

**Comment by gypark23** [comment]
@Strongbrother1 My works at https://github.com/gypark23/Geo-Mafia/actions
