### ISSUE TITLE
Update Implementation of Maps to Facilitate Integration

### ISSUE THREAD

**Issue by corian-jal** [Geo-Mafia/Geo-Mafia#51]
The implementation of map and bubble needs to be updated to a hashmap in order to integrate with the work done by the other teams. After PR #41 goes through, I will review the usage of map/bubble across the different modules and standardize them to the implementation of a hashmap map.

**Comment by nd1az** [comment]
I created a branch for this issue. I'll assign myself to it so that I can add bubbles in the CampusMap class that correspond to other locations on campus

**Comment by corian-jal** [comment]
I changed the list of players in bubble to a map of player.userID and player before updating the list-specific implementation of the list to a map-based implementation for map.component.ts and map_tests.spec.tests.js. 

Notes: I tried to change map_tests.spec.js to a .ts file or just to pull from map.component.ts instead of map.component.js, but it led to problems I could not figure out how to resolve, so I decided to leave that change to the file type update issue. Otherwise, there were no problems at the time of committing, though I'm not sure if it compiles or the tests run due to difficulty compiling on my machine. It should also be noted that location does not allow for the input of fake values to test inBubble, so I coded those tests with an approximation that may or may not work.

**Comment by corian-jal** [comment]
Successfully changed map_tests.spec.tests.js to map_tests.spec.tests.ts with no problems reported by VSCode.

**Comment by nd1az** [comment]
I did some minor updates because there were quite a bit of errors afterwards. 
I am also proposing a change to the checkBubble fn in the CampusMap component file, there is a comment there, I will be moving on to check the game class out, but I will be making a pull request so that these changes get to everyone.
